# -*- coding: utf-8 -*-
"""23UAM028.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1melzF1FVvZCSoQYqUGBvIatKprtizs3U
"""

salary=int(input("Enter salary"))
if(salary>50000):print("High income")
elif(salary>=30000 and salary<=50000):print("Medium Income")
elif(salary<=30000):print("low Income")

street_light=int(input("Enter Streetlight number"))
if((street_light%2==0)):
  print(f"Streetlight{street_light}will be turn on at night")
else:
  print(f"Streetlight{street_light}will be turn on at night")

print("1. Check Balance")
print("2. Deposit Money")
print("3. Withdraw Money")
print("4. Exit the system")

Balance = 10000

while True:
    choice = int(input("Enter your choice: "))

    if choice == 1:
        print(f"Your account balance is: {Balance}")

    elif choice == 2:
        bal = int(input("Enter money to deposit: "))
        Balance += bal
        print(f"Your current balance is: {Balance}")

    elif choice == 3:
        wit = int(input("Enter money to withdraw: "))
        if wit > Balance:
            print("Insufficient balance!")
        else:
            Balance -= wit
            print(f"Your current balance is: {Balance}")

    elif choice == 4:
        print("Exiting the system. Goodbye!")
        break

    else:
        print("Invalid choice. Please enter a valid option.")

total_passengers = 0

for stop in range(1, 6):
    passengers = int(input(f"Enter the number of passengers at stop {stop}: "))
    total_passengers += passengers

print(f"Total number of passengers at the end: {total_passengers}")

correct_pin = 1234
attempts = 0

while attempts < 3:
    entered_pin = int(input("Enter your ATM PIN: "))

    if entered_pin == correct_pin:
        print("Access granted! Welcome.")
        break
    else:
        attempts += 1
        remaining_attempts = 3 - attempts
        if remaining_attempts > 0:
            print(f"Incorrect PIN. You have {remaining_attempts} attempts left.")
        else:
            print("Incorrect PIN. Your card is blocked.")

num = int(input("Enter a number: "))
reversed_num = int(str(num)[::-1])
print(f"Reversed number: {reversed_num}")

def shopping_cart():
    cart = []

    while True:
        item = input("Enter an item to add to the cart (or type 'done' to finish): ").strip()
        if item.lower() == "done":
            break
        cart.append(item)

    print("\nShopping Cart Items:")
    for idx, item in enumerate(cart, start=1):
        print(f"{idx}. {item}")


shopping_cart()

def atm_cash_dispense(amount):
    if amount % 500 != 0:
        print("Invalid amount! Please enter an amount that is a multiple of 500.")
        return

    notes_2000 = amount
    remaining_amount = amount % 2000
    notes_500 = remaining_amount
    print(f"\nCash Dispensed:")
    print(f"₹2000 notes: {notes_2000}")
    print(f"₹500 notes: {notes_500}")

# User input
amount = int(input("Enter the amount to withdraw (multiple of 500): "))
atm_cash_dispense(amount)

def student_grades():
    grades = tuple(map(int, input("Enter 5 grades separated by spaces: ").split()))

    if len(grades) != 5:
        print("Please enter exactly 5 grades.")
        return

    highest = max(grades)
    lowest = min(grades)
    average = sum(grades) / len(grades)

    print(f"Highest Grade: {highest}")
    print(f"Lowest Grade: {lowest}")
    print(f"Average Grade: {average:.2f}")

# Run the function
student_grades()